import pyautogui,time
def presshotkey(key1,key2):pyautogui.hotkey(key1,key2)
def moveclick(x,y):pyautogui.moveTo(x,y);pyautogui.click()
def press(key):pyautogui.press(key);time.sleep(1)
def type(text):pyautogui.typewrite(text)
moveclick(47,1045)
moveclick(125,150)
type('run')
press('enter')
press('backspace')
type('%temp%')
press('enter')
presshotkey('ctrl','a')
press('delete')
for i in range(0,4):press('escape')
moveclick(1885,25)
moveclick(47,1045)
type('cmd')
press('enter')
type('ipconfig /flushdns')
press('enter')
type('exit')
press('enter')
moveclick(47,1045)
type('disk cleanup')
for i in range(0,4):press('enter')
