
#!GITHUB AND DRIVE UPDATE
#TODO: Find all ways in which unwanted files can be cleared
import pyautogui
import time
pyautogui.moveTo(47,1045)
pyautogui.click()
pyautogui.moveTo(125,150)
pyautogui.click()
pyautogui.typewrite("Disk Cleanup")
pyautogui.press("Enter")
time.sleep(1)
pyautogui.press("Enter")
time.sleep(1)
pyautogui.press("Enter")
time.sleep(1)
pyautogui.press("Enter")
time.sleep(30)
pyautogui.moveTo(47,1045)
pyautogui.click()
pyautogui.typewrite("Command prompt")
pyautogui.press("Enter")
time.sleep(2)
pyautogui.typewrite("ipconfig /flushdns")
pyautogui.press("Enter")
pyautogui.typewrite("exit")
pyautogui.press("Enter")
pyautogui.moveTo(47,1045)
pyautogui.click()
pyautogui.moveTo(125,150)
pyautogui.click()
pyautogui.typewrite("Run")
pyautogui.press("Enter")
time.sleep(1)
pyautogui.press("backspace")
pyautogui.typewrite("%temp%")
pyautogui.press("Enter")
time.sleep(1)
pyautogui.hotkey('ctrl', 'a')
pyautogui.press('delete')
time.sleep(1)
pyautogui.moveTo(670,550)
pyautogui.click()
pyautogui.moveTo(1035,600)
pyautogui.click()
pyautogui.moveTo(670,550)
pyautogui.click()
pyautogui.moveTo(1035,600)
pyautogui.click()
pyautogui.moveTo(670,550)
pyautogui.click()
pyautogui.moveTo(1035,600)
pyautogui.click()