import pyautogui
import time
pyautogui.moveTo(47,1045)
pyautogui.click()
pyautogui.moveTo(125,150)
pyautogui.click()
pyautogui.typewrite("Run")
pyautogui.press("Enter")
time.sleep(1)
pyautogui.press("backspace")
pyautogui.typewrite("%temp%")
pyautogui.press("Enter")
time.sleep(1)
pyautogui.hotkey('ctrl','a')
pyautogui.press('delete')
pyautogui.press('escape')
pyautogui.press('escape')
pyautogui.press('escape')
pyautogui.press('escape')
pyautogui.moveTo(1885,25)
pyautogui.click()
pyautogui.press("Enter")
pyautogui.moveTo(47,1045)
pyautogui.click()
pyautogui.typewrite("Command prompt")
pyautogui.press("Enter")
time.sleep(2)
pyautogui.typewrite("ipconfig /flushdns")
pyautogui.press("Enter")
pyautogui.typewrite("exit")
pyautogui.press("Enter")
pyautogui.moveTo(47,1045)
pyautogui.click()
pyautogui.moveTo(125,150)
pyautogui.click()
pyautogui.typewrite("Disk Cleanup")
pyautogui.press("Enter")
time.sleep(1)
pyautogui.press("Enter")
time.sleep(1)
pyautogui.press("Enter")
time.sleep(1)
pyautogui.press("Enter")
time.sleep(1)
pyautogui.press("Enter")
