import pyautogui,time
def presshotkey(key1,key2):pyautogui.hotkey(key1,key2)
def moveandclick(x,y):pyautogui.moveTo(x,y);pyautogui.click()
def press(key):time.sleep(1);pyautogui.press(key)
def type(text):pyautogui.write(text)
moveandclick(47,1045)
moveandclick(125,150)
type('run')
press('enter')
press('backspace')
type('%temp%')
press('enter')
presshotkey('ctrl','a')
press('delete')
for i in range(0,4):press('escape')
moveandclick(1885,25)
press('enter')
moveandclick(47,1045)
type('cmd')
press('enter')
type('ipconfig /flushdns')
press('enter')
type('exit')
press('enter')
moveandclick(47,1045)
type('disk cleanup')
for i in range(0,4):press('enter')
